#! /bin/bash
echo -e "Compiling with 
  g++ -std=gnu++14 -Wall -g -Wextra -Wshadow -Wfloat-equal -fmax-errors=1 -Wconversion -Wshift-overflow=2 -Wduplicated-cond -O2"

if #compilation
  rm -rf ./a.out
  g++ -std=gnu++14 -Wall -g -Wextra -Wshadow -Wfloat-equal -fmax-errors=1 -Wconversion -Wshift-overflow=2 -Wduplicated-cond -DCONVICTION -O2 $1
then #if compilation successful
  echo -e "\e[32m\e[1mCompilation Successful!\e[0m"
else
  echo -e "\e[91m\e[1mCompilation Error!\e[0m";
fi
echo -e "____________________________________________"
